version: '3.7'
services:
  mongo:
    container_name: mongo-tashilkar
    image: mongo
    ports:
      - "27017:27017"
    command: mongod
    environment:
      MONGODB_USER: "tashilkar"
      MONGODB_PASS: "123456"
  ########################################
  health_checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tashilkar_health_checker
    image: tashilkar_health_checker
    ports:
      - "3001:3001"
    depends_on:
      - mongo
  ########################################
  webhook:
    build:
      context: ../webhook
      dockerfile: Dockerfile
    container_name: webhook
    image: saeedsrc/webhook
    ports:
      - "3000:3000"