webhook_url: "http://webhook:3000/api/v1/update"
port: "3001"
down_message: "system is down"
crash_message: "system is crashed"
stoppage_time: 10
mongo:
  uri: "mongodb://mongodb:27017"
  database: "tashilkar"
  collections: ["endpoints", "checked_endpoints", "health_checker_availability"]