version: "3.9"
services:
  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - tashilkar
  ########################################
  health_checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tashilkar_health_checker
    ports:
      - "3001:3001"
    networks:
      - tashilkar
    links:
      - mongodb
    depends_on:
      - mongodb
  ########################################
  webhook:
    build:
      context: ../webhook
      dockerfile: Dockerfile
    container_name: webhook
    ports:
      - "3000:3000"
    networks:
      - tashilkar
networks:
  tashilkar: